library(tidyverse)
setwd("~/Desktop/census_tract")
df <- read_csv('SEPTA__Regional_Rail_Stations.csv')
df2 <- filter(df, County == 'Philadelphia')
names(df2)
df3 <- select(df2, Station_Name,Street_Address, City,Zip,State,Weekday_Total_Boards,Weekday_Total_Leaves,Saturday_Total_Boards,Saturday_Total_Leaves,Sunday_Total_Boards,Sunday_Total_Leaves,X,Y )
write.csv(df3, 'regional_rail.csv')
#################################################3
df <- read_csv('SEPTA__MarketFrankford_Line_Stations.csv')
df2 <- filter(df, County == 'Philadelphia')
names(df2)
df3 <- select(df2,Station, Street_Address, City, State, Zip,Average_Weekday_Ridership,Average_Saturday_Ridership,Average_Sunday_Ridership,X,Y )
write.csv(df3, 'MF_line.csv')
#################################################3
df <- read_csv('SEPTA__Broad_Street_Line_Stations.csv')
df2 <- filter(df, County == 'Philadelphia')
names(df2)
df3 <- select(df2,Station, Street_Address, City, State, Zip,Average_Weekday_Ridership,Average_Saturday_Ridership,Average_Sunday_Ridership,X,Y )
write.csv(df3, 'BS_line.csv')
#################################################
df <- read_csv('Subway_Stops.csv')
names(df)
man <- filter(df,Borough == 'M' )
man2 <- select(man, 'Stop Name', 'Daytime Routes','GTFS Latitude','GTFS Longitude')
write.csv(man2, 'nyc_location.csv')
