library(sf)
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(ggthemes)
library(scales)
library(mapdata)
library(tigris)
library(mapproj)
library(readr)
setwd("~/Desktop")
star <- read.csv('Us_starbucks_no_A.csv', colClasses=c("New_Postcode"="character"))
nyc <- filter(star, City == 'New York')
nyc$X <- NULL
table(nyc$New_Postcode)
length(unique(nyc$New_Postcode))
#####################3
zt <- read_csv('zip_to_zcta_2019.csv')
write.csv(nyc, file = 'Star_nyc')
